# run-git-filter-repo.ps1
# This script is generated by prepare-scrub.ps1 and contains the exact commands
# to run git-filter-repo on the mirror clone you previously created.

# WARNING: The commands below are commented out by default. EDIT the `$REMOTE_URL` variable
# and uncomment the commands only when you fully understand the impact.


$REMOTE_URL = 'https://github.com/your-org/pos-website.git'  # <<< EDIT ME BEFORE RUNNING

Write-Host "RUN SCRIPT NOTICE: This script will rewrite git history and requires a force-push." -ForegroundColor Yellow
Write-Host "Edit the REMOTE_URL above, verify replacements.txt exists in the mirror clone, then uncomment commands in this file to execute." -ForegroundColor Yellow
Write-Host "Current REMOTE_URL is: $REMOTE_URL" -ForegroundColor Cyan

# Example commands (commented out). Uncomment to execute.

# cd ..\pos-website-mirror.git
# git filter-repo --replace-text replacements.txt
# # If you instead want to remove specific paths completely:
# # git filter-repo --invert-paths --paths .env --paths php-backend/.env
# 
# # Force-push rewritten history
# git remote set-url origin $REMOTE_URL
# git push --force --all
# git push --force --tags

Write-Host "Run script created. Review and run manually when ready." -ForegroundColor Green
